import type { Metadata } from "next";
import { Open_Sans, Nunito } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Suspense } from "react";

const inter = Nunito({
  weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Sidebar />
        <main className="mx-5 mt-16 sm:ml-[300px] sm:mt-3">{children}</main>
      </body>
    </html>
  );
}
